apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
data:
  lnd.conf: |-
  {{- if .Values.p2pService.listen }}
    listen=0.0.0.0:{{ .Values.p2pService.port }}
  {{- end}}
  {{- if ne .Values.global.network "regtest" }}
    wallet-unlock-password-file=/tmp/wallet-password
    wallet-unlock-allow-create=true
  {{- end }}
  {{- range .Values.lndGeneralConfig }}
    {{ . }}
  {{- end }}
  {{- range .Values.configmap.customValues }}
    {{ . }}
  {{- end }}
    tlsextradomain={{ include "lnd.fullname" . }}
  {{- if .Values.apiService.staticIP }}
    tlsextraip={{ .Values.apiService.staticIP }}
  {{- end}}
  {{- if .Values.alias }}
    alias={{ include "lnd.fullname" . }}-{{ .Values.alias }}
  {{- end}}
  {{- if .Values.p2pService.staticIP }}
    tlsextraip={{ .Values.p2pService.staticIP }}
    externalip={{ .Values.p2pService.staticIP }}:{{ .Values.p2pService.port }}
  {{- end}}
  {{- if .Values.extdomain }}
    externalhosts={{ include "lnd.fullname" . }}.{{ .Values.extdomain }}:{{ .Values.p2pService.port }}
    tlsextradomain={{ include "lnd.fullname" . }}.{{ .Values.extdomain }}
  {{- end}}